spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}            # 배포용 DB 주소를 환경 변수로 관리
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379

# .env 파일에서 로드될 변수들:
# DB_USERNAME, DB_PASSWORD
# AWS_ACCESS_KEY, AWS_SECRET_KEY
